# Generated by Django 2.1.5 on 2020-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200515_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(to='products.IngredientPrice'),
        ),
    ]
