# Generated by Django 2.1.5 on 2020-05-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores_accounts', '0002_auto_20200502_1242'),
        ('cart', '0003_auto_20200516_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores_accounts.Store'),
            preserve_default=False,
        ),
    ]
