# Generated by Django 2.1.5 on 2020-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200520_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'PickUpTime',
            },
        ),
    ]
