# Generated by Django 2.2 on 2020-05-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.PickUpTime'),
            preserve_default=False,
        ),
    ]
