# Generated by Django 2.2 on 2020-05-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_accounts', '0005_auto_20200526_1146'),
        ('cart', '0010_auto_20200527_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers_accounts.CustomerProfile'),
            preserve_default=False,
        ),
    ]
