# Generated by Django 2.2 on 2020-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_ordered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
