# Generated by Django 2.1.5 on 2020-05-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_accounts', '0003_customerprofile_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerprofile',
            unique_together=set(),
        ),
    ]
