# Generated by Django 2.1.5 on 2020-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200508_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
