# Generated by Django 2.1.5 on 2020-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200508_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
